kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: l.gcr.io/google/bazel:latest
    commands:
      - echo "build --disk_cache=/cache/funcheck" >> .bazelrc
      - bazel test --color=yes --curses=yes //...
