kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: l.gcr.io/google/bazel:latest
    volumes:
      - name: cache
        path: /todo
    commands:
      - echo "build --disk-cache=/cache" >> .bazelrc
      - bazel test //...

volumes:
  - name: cache
    host:
      path: /cache/funcheck
