version: '2'

vars:
  BZL_OPTS: "--color=yes --curses=yes"

tasks:
  build:
    cmds:
      - bazel build {{.BZL_OPTS}} $(bazel query 'kind(go_binary, //...)')
  test:
    cmds:
      - bazel test {{.BZL_OPTS}} //...
  default:
    cmds:
      - task: test
      - task: build
